
ALTER TABLE public.applications
  ADD COLUMN IF NOT EXISTS application_type text,
  ADD COLUMN IF NOT EXISTS middle_name text,
  ADD COLUMN IF NOT EXISTS surname text,
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS contact_no text,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS permanent_address text,
  ADD COLUMN IF NOT EXISTS current_address text,
  ADD COLUMN IF NOT EXISTS reference text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS is_qualified_ca boolean,
  ADD COLUMN IF NOT EXISTS membership_no text,
  ADD COLUMN IF NOT EXISTS icai_certified_courses text,
  ADD COLUMN IF NOT EXISTS school_institute text,
  ADD COLUMN IF NOT EXISTS school_year integer,
  ADD COLUMN IF NOT EXISTS school_specialization text,
  ADD COLUMN IF NOT EXISTS school_percentage numeric,
  ADD COLUMN IF NOT EXISTS graduation_institute text,
  ADD COLUMN IF NOT EXISTS graduation_year integer,
  ADD COLUMN IF NOT EXISTS graduation_specialization text,
  ADD COLUMN IF NOT EXISTS graduation_percentage numeric,
  ADD COLUMN IF NOT EXISTS post_graduation_institute text,
  ADD COLUMN IF NOT EXISTS post_graduation_year integer,
  ADD COLUMN IF NOT EXISTS post_graduation_specialization text,
  ADD COLUMN IF NOT EXISTS post_graduation_percentage numeric,
  ADD COLUMN IF NOT EXISTS other_qualification_institute text,
  ADD COLUMN IF NOT EXISTS other_qualification_year integer,
  ADD COLUMN IF NOT EXISTS other_qualification_specialization text,
  ADD COLUMN IF NOT EXISTS other_qualification_percentage numeric,
  ADD COLUMN IF NOT EXISTS employer_name text,
  ADD COLUMN IF NOT EXISTS employment_from date,
  ADD COLUMN IF NOT EXISTS employment_to date,
  ADD COLUMN IF NOT EXISTS last_designation text,
  ADD COLUMN IF NOT EXISTS area_of_interest text,
  ADD COLUMN IF NOT EXISTS post_qualification_years integer,
  ADD COLUMN IF NOT EXISTS post_qualification_months integer,
  ADD COLUMN IF NOT EXISTS current_ctc text,
  ADD COLUMN IF NOT EXISTS expected_ctc text,
  ADD COLUMN IF NOT EXISTS notice_period text,
  ADD COLUMN IF NOT EXISTS is_transfer_case boolean,
  ADD COLUMN IF NOT EXISTS transfer_case_details text;

-- Make old required columns nullable since new form structure differs
ALTER TABLE public.applications
  ALTER COLUMN ca_level DROP NOT NULL,
  ALTER COLUMN applying_for DROP NOT NULL,
  ALTER COLUMN domain DROP NOT NULL,
  ALTER COLUMN phone DROP NOT NULL;
